local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
    s("prefsmall", {
        t({
            "Task:",
        }),
        i(1, "{{task}}"),
        t({
            "",
            "",
            "Context:",
        }),
        i(2, "{{context}}"),
        t({
            "",
            "",
            "Operate in single-agent mode unless the task clearly requires decomposition.",
            "",
            "Workflow:",
            "1. Inspect the relevant project context, files, configuration, or materials first.",
            "2. Summarize the problem and identify assumptions, risks, or unknowns.",
            "3. Create a minimal plan appropriate to the task size.",
            "4. Execute only the scoped changes or deliverables needed.",
            "5. Verify using the strongest relevant checks available for this task type.",
            "6. Report the result, caveats, and any follow-up needs.",
            "",
            "Rules:",
            "- Ground decisions in observed project reality, not guesses.",
            "- Follow existing conventions and patterns.",
            "- Avoid unnecessary abstraction, ceremony, or unrelated edits.",
            "- Distinguish observations from assumptions.",
            "- Do not invent requirements, architecture, or behavior.",
            "- If the task turns out to be larger or riskier than expected, say so clearly.",
            "- Update existing documentation only if the verified change meaningfully affects usage, behavior, maintenance, or future work.",
            "",
            "Final output:",
            "1. Task understanding",
            "2. Assumptions or unknowns",
            "3. Plan",
            "4. Changes made or proposed",
            "5. Verification results",
            "6. Risks / caveats",
            "7. Final status",
        }),
    }),
    s("prefmulti", {
        t({
            "You are the manager agent for a substantial task in an existing project.",
            "",
            "Primary objective:",
        }),
        i(1, "{{task}}"),
        t({
            "",
            "",
            "Project/context:",
        }),
        i(2, "{{context}}"),
        t({
            "",
            "",
            "Manager responsibilities:",
            "- Ground all decisions in inspected code, configuration, documentation, tests, logs, or other relevant materials.",
            "- Preserve existing architecture and conventions unless the task clearly requires change.",
            "- Prefer incremental, coherent changes over sweeping rewrites.",
            "- Distinguish observations, inferences, and assumptions.",
            "- Avoid unnecessary abstraction, process overhead, and speculative edits.",
            "",
            "Phase 1: Scoped decomposition",
            "- Define the real problem scope.",
            "- Identify the task type: debugging, implementation, refactor, writing, operations, research, or mixed.",
            "- Decide whether subagents are actually justified.",
            "- Define success criteria, constraints, risks, and likely verification methods.",
            "",
            "Phase 2: Parallel investigation",
            "- Use only the subagents that are genuinely useful for the task.",
            "- Each subagent must investigate a distinct angle and return:",
            "  - findings",
            "  - evidence",
            "  - relevant files / components / artifacts",
            "  - constraints",
            "  - risks",
            "  - recommendations",
            "",
            "Possible investigation angles include:",
            "- existing implementation and architecture",
            "- interfaces, APIs, data flow, and dependencies",
            "- tests, logs, configuration, and environment",
            "- conventions, naming, and prior patterns",
            "- edge cases, regressions, and operational risks",
            "- documentation, usage expectations, and maintenance impact",
            "",
            "Phase 3: Manager synthesis",
            "- Reconcile conflicting findings.",
            "- State the preferred path and why it is preferred.",
            "- Define scope boundaries.",
            "- Identify preserved behaviors and invariants.",
            "- List major risks and open assumptions.",
            "- Note rejected alternatives when relevant.",
            "",
            "Phase 4: Planning",
            "- Before making changes, create a concrete plan that includes:",
            "  - ordered steps",
            "  - expected files or artifacts to modify",
            "  - dependencies and prerequisites",
            "  - rollback or containment considerations when relevant",
            "  - verification strategy",
            "  - documentation impact, if any",
            "- Do not proceed until the plan is consistent with the evidence gathered.",
            "",
            "Phase 5: Execution",
            "- Make clean, scoped changes aligned with the approved plan.",
            "- Reuse existing patterns where possible.",
            "- Avoid unrelated edits.",
            "- If new evidence invalidates the plan, stop and revise before continuing.",
            "",
            "Phase 6: Verification",
            "- Validate using the strongest relevant checks available for the task type, such as:",
            "  - tests",
            "  - static analysis",
            "  - build / lint / type checks",
            "  - reproduction of the original issue",
            "  - runtime validation",
            "  - content review or factual consistency checks",
            "  - manual inspection where stronger checks are unavailable",
            "- Do not claim success without stating what was actually verified.",
            "",
            "Phase 7: Documentation and handoff",
            "- Update existing documentation only when the final verified result changes usage, behavior, operations, maintenance, or future development expectations.",
            "- Prefer existing documentation locations and conventions.",
            "- Do not create new documentation structure unless there is no suitable existing location and documentation is clearly warranted.",
            "- Do not document behavior that was not implemented and verified.",
            "",
            "Retry policy:",
            "- Retry only if failure produced materially new information.",
            "- Revise investigation, synthesis, and planning before another attempt.",
            "- Do not repeat substantially similar attempts.",
            "- Stop after 3 materially distinct attempts or earlier if blocked by external constraints.",
            "",
            "Final output:",
            "1. Task decomposition",
            "2. Investigation findings",
            "3. Synthesis and chosen strategy",
            "4. Implementation plan",
            "5. Changes made",
            "6. Verification results",
            "7. Documentation updates",
            "8. Risks, caveats, and blockers",
            "9. Final status",
        }),
    }),
}
